### ISSUE TITLE
mysql error

### ISSUE THREAD

**Issue by btrspg** [LPM-HMS/COSMOS2#95]
Hi there~:

I want store the workflow in mysql, so I test this:

```python
def word_count(in_txt, out_txt, use_lines=False):
    l = ' -l' if use_lines else ''
    return r"""
        ls{l} > {out_txt}
        """.format(**locals())




def main():
    cosmos = Cosmos('mysql+pymysql://cosmos:123@localhost/cosmos2_workflow')
    cosmos.initdb()
    workflow = cosmos.start('My_Workflow', skip_confirm=True)

    wc_tasks = [workflow.add_task(word_count, params=dict(in_txt=inp, out_txt=out),
                                  uid=str(i))
                for i, (inp, out) in enumerate((('a.txt', 'a_out.txt'), ('b.txt', 'b_out.txt')))]

    # note this will create a_out.txt and b_out.txt in your current directory
    workflow.run()
```
But it goes error like below, which is `sqlalchemy.exc.CompileError: (in table 'workflow', column '_status'): VARCHAR requires a length on dialect mysql`

How can I fix this error.

```
Initializing sql database for Cosmos v2.6.24...
Traceback (most recent call last):
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 2463, in visit_create_table
    and not first_pk)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 245, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 2494, in visit_create_column
    first_pk=first_pk
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/dialects/mysql/base.py", line 1133, in get_column_specification
    column.type, type_expression=column)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 293, in process
    return type_._compiler_dispatch(self, **kw)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 2953, in visit_type_decorator
    return self.process(type_.type_engine(self.dialect), **kw)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 293, in process
    return type_._compiler_dispatch(self, **kw)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 2933, in visit_string
    return self.visit_VARCHAR(type_, **kw)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/dialects/mysql/base.py", line 1540, in visit_VARCHAR
    self.dialect.name)
sqlalchemy.exc.CompileError: VARCHAR requires a length on dialect mysql

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "cosmos_demo.py", line 39, in <module>
    main()
  File "cosmos_demo.py", line 27, in main
    cosmos.initdb()
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/cosmos/models/Cosmos.py", line 244, in initdb
    Base.metadata.create_all(bind=self.session.bind)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 4004, in create_all
    tables=tables)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1940, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1549, in _run_visitor
    **kwargs).traverse_single(element)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 757, in visit_metadata
    _is_metadata_operation=True)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 791, in visit_table
    include_foreign_key_constraints=include_foreign_key_constraints
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1003, in _execute_ddl
    if not self.schema_for_object.is_default else None)
  File "<string>", line 1, in <lambda>
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 442, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 26, in _compiler
    return dialect.ddl_compiler(dialect, self, **kw)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 219, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 245, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 2474, in visit_create_table
    (table.description, column.name, ce.args[0])
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 2463, in visit_create_table
    and not first_pk)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 245, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 2494, in visit_create_column
    first_pk=first_pk
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/dialects/mysql/base.py", line 1133, in get_column_specification
    column.type, type_expression=column)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 293, in process
    return type_._compiler_dispatch(self, **kw)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 2953, in visit_type_decorator
    return self.process(type_.type_engine(self.dialect), **kw)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 293, in process
    return type_._compiler_dispatch(self, **kw)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 2933, in visit_string
    return self.visit_VARCHAR(type_, **kw)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/dialects/mysql/base.py", line 1540, in visit_VARCHAR
    self.dialect.name)
sqlalchemy.exc.CompileError: (in table 'workflow', column '_status'): VARCHAR requires a length on dialect mysq
```

**Comment by egafni** [comment]
I tried to fix this in 2.8.1 and released to pypi, can you try it out?  I don't have mysql installed to test

here's the commit:
https://github.com/LPM-HMS/COSMOS2/commit/a37c25e0c411c2d4c91eb795e382732328a7710a

**Comment by btrspg** [comment]
Hi @egafni 
Thank you for reply me so soon.

I have tried the `a37c25e`

There are some other errors occur:


>_mysql_exceptions.OperationalError: (1101, "BLOB, TEXT, GEOMETRY or JSON column 'params' can't have a default value")


details are below:

```
Initializing sql database for Cosmos v2.8.0...
Traceback (most recent call last):
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 508, in do_execute
    cursor.execute(statement, parameters)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1101, "BLOB, TEXT, GEOMETRY or JSON column 'params' can't have a default value")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "cosmos_demo.py", line 39, in <module>
    main()
  File "cosmos_demo.py", line 27, in main
    cosmos.initdb()
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/cosmos/models/Cosmos.py", line 248, in initdb
    Base.metadata.create_all(bind=self.session.bind)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 4004, in create_all
    tables=tables)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1940, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1549, in _run_visitor
    **kwargs).traverse_single(element)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 757, in visit_metadata
    _is_metadata_operation=True)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 791, in visit_table
    include_foreign_key_constraints=include_foreign_key_constraints
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1009, in _execute_ddl
    compiled
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 508, in do_execute
    cursor.execute(statement, parameters)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
# @Software: PyCharm
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1101, "BLOB, TEXT, GEOMETRY or JSON column 'params' can't have a default value") [SQL: "\nCREATE TABLE task (\n\tid INTEGER NOT NULL AUTO_INCREMENT, \n\tuid VARCHAR(255), \n\tmem_req INTEGER, \n\tcore_req INTEGER, \n\ttime_req INTEGER, \n\t`NOOP` BOOL NOT NULL, \n\tparams TEXT NOT NULL DEFAULT '{}', \n\tstage_id INTEGER NOT NULL, \n\tlog_dir VARCHAR(255), \n\t_status VARCHAR(255) NOT NULL, \n\tsuccessful BOOL NOT NULL, \n\tstarted_on DATETIME, \n\tsubmitted_on DATETIME, \n\tfinished_on DATETIME, \n\tattempt INTEGER NOT NULL, \n\tmust_succeed BOOL NOT NULL, \n\tdrm VARCHAR(255), \n\tqueue VARCHAR(255), \n\tmax_attempts INTEGER, \n\tinput_map TEXT NOT NULL DEFAULT '{}', \n\toutput_map TEXT NOT NULL DEFAULT '{}', \n\tdrm_native_specification VARCHAR(255), \n\t`drm_jobID` VARCHAR(255), \n\texit_status INTEGER, \n\tpercent_cpu INTEGER, \n\twall_time INTEGER, \n\tcpu_time INTEGER, \n\tuser_time INTEGER, \n\tsystem_time INTEGER, \n\tavg_rss_mem_kb INTEGER, \n\tmax_rss_mem_kb INTEGER, \n\tavg_vms_mem_kb INTEGER, \n\tmax_vms_mem_kb INTEGER, \n\tio_read_count INTEGER, \n\tio_write_count INTEGER, \n\tio_wait INTEGER, \n\tio_read_kb INTEGER, \n\tio_write_kb INTEGER, \n\tctx_switch_voluntary INTEGER, \n\tctx_switch_involuntary INTEGER, \n\tavg_num_threads INTEGER, \n\tmax_num_threads INTEGER, \n\tavg_num_fds INTEGER, \n\tmax_num_fds INTEGER, \n\textra TEXT NOT NULL DEFAULT '{}', \n\tPRIMARY KEY (id), \n\tCONSTRAINT _uc1 UNIQUE (stage_id, uid), \n\tCHECK (`NOOP` IN (0, 1)), \n\tFOREIGN KEY(stage_id) REFERENCES stage (id) ON DELETE CASCADE, \n\tCHECK (successful IN (0, 1)), \n\tCHECK (must_succeed IN (0, 1))\n)\n\n"] (Background on this error at: http://sqlalche.me/e/e3q8)
(py_cosmos) chenyl@chenyl-ubuntu:~/PROJECTS/cosmos2$ vi cosmos_demo.py
(py_cosmos) chenyl@chenyl-ubuntu:~/PROJECTS/cosmos2$ python cosmos_demo.py
Initializing sql database for Cosmos v2.8.0...
Traceback (most recent call last):
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 508, in do_execute
    cursor.execute(statement, parameters)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1101, "BLOB, TEXT, GEOMETRY or JSON column 'params' can't have a default value")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "cosmos_demo.py", line 39, in <module>
    main()
  File "cosmos_demo.py", line 27, in main
    cosmos.initdb()
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/cosmos/models/Cosmos.py", line 248, in initdb
    Base.metadata.create_all(bind=self.session.bind)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 4004, in create_all
    tables=tables)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1940, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1549, in _run_visitor
    **kwargs).traverse_single(element)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 757, in visit_metadata
    _is_metadata_operation=True)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 791, in visit_table
    include_foreign_key_constraints=include_foreign_key_constraints
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1009, in _execute_ddl
    compiled
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 508, in do_execute
    cursor.execute(statement, parameters)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/home/chenyl/.virtualenvs/py_cosmos/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1101, "BLOB, TEXT, GEOMETRY or JSON column 'params' can't have a default value") [SQL: "\nCREATE TABLE task (\n\tid INTEGER NOT NULL AUTO_INCREMENT, \n\tuid VARCHAR(255), \n\tmem_req INTEGER, \n\tcore_req INTEGER, \n\ttime_req INTEGER, \n\t`NOOP` BOOL NOT NULL, \n\tparams TEXT NOT NULL DEFAULT '{}', \n\tstage_id INTEGER NOT NULL, \n\tlog_dir VARCHAR(255), \n\t_status VARCHAR(255) NOT NULL, \n\tsuccessful BOOL NOT NULL, \n\tstarted_on DATETIME, \n\tsubmitted_on DATETIME, \n\tfinished_on DATETIME, \n\tattempt INTEGER NOT NULL, \n\tmust_succeed BOOL NOT NULL, \n\tdrm VARCHAR(255), \n\tqueue VARCHAR(255), \n\tmax_attempts INTEGER, \n\tinput_map TEXT NOT NULL DEFAULT '{}', \n\toutput_map TEXT NOT NULL DEFAULT '{}', \n\tdrm_native_specification VARCHAR(255), \n\t`drm_jobID` VARCHAR(255), \n\texit_status INTEGER, \n\tpercent_cpu INTEGER, \n\twall_time INTEGER, \n\tcpu_time INTEGER, \n\tuser_time INTEGER, \n\tsystem_time INTEGER, \n\tavg_rss_mem_kb INTEGER, \n\tmax_rss_mem_kb INTEGER, \n\tavg_vms_mem_kb INTEGER, \n\tmax_vms_mem_kb INTEGER, \n\tio_read_count INTEGER, \n\tio_write_count INTEGER, \n\tio_wait INTEGER, \n\tio_read_kb INTEGER, \n\tio_write_kb INTEGER, \n\tctx_switch_voluntary INTEGER, \n\tctx_switch_involuntary INTEGER, \n\tavg_num_threads INTEGER, \n\tmax_num_threads INTEGER, \n\tavg_num_fds INTEGER, \n\tmax_num_fds INTEGER, \n\textra TEXT NOT NULL DEFAULT '{}', \n\tPRIMARY KEY (id), \n\tCONSTRAINT _uc1 UNIQUE (stage_id, uid), \n\tCHECK (`NOOP` IN (0, 1)), \n\tFOREIGN KEY(stage_id) REFERENCES stage (id) ON DELETE CASCADE, \n\tCHECK (successful IN (0, 1)), \n\tCHECK (must_succeed IN (0, 1))\n)\n\n"] (Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by egafni** [comment]
assuming its fixed by your PR!
